blog/urls.py
from django.urls import path
from .import views as blog

app_name="blog"
urlpatterns = [
         path('', blog.index, name='index'),
         path('un_article/<int:id>', blog.un_article, name='un_article'),
]

commanderie/urls.py
from django.urls import path

from . import views

urlpatterns = [
         path('', views.commandview, name='commandview'),
]

districte/urls.py
from django.urls import path

from . import views

urlpatterns = [
         path('', views.indexdist, name='indexdist'),
]

saint_jonh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^blog/', include('blog.urls')),
    url(r'^commanderie/', include('commanderie.urls')),
    url(r'^districte/', include('districte.urls')),
    url(r'^admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.

class Categorie(models.Model):
    name = models.CharField(" name", max_length=100, blank=True, null=True)
    
    

    class Meta:
        verbose_name = _("Categorie")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("categorie_detail", kwargs={"pk": self.pk})
    
class Article(models.Model):
    name = models.CharField(("nom de l'articles"), max_length=100, blank=True, null=True)
    publication = models.DateTimeField(("date de publication"), blank=True, null=True)
    categories = models.ForeignKey(Categorie, related_name='categories', on_delete=models.CASCADE)
    description = models.TextField(("description"), null = True, blank=True)
    picture= models.ImageField( upload_to="pictures/", null = True, blank=True)
    
    
    
    
    

    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"pk": self.pk})
    
    

commanderie/models.py
from django.db import models
from django.utils.translation import gettext as _
from districte.models import Section
# Create your models here.

class Commanderie(models.Model):
    name = models.CharField("nom commanderie",max_length=100, blank=True, null=True)
    numero = models.PositiveSmallIntegerField(_("numéro commanderie"))
    date = models.DateField(_("date de création"), auto_now=False)
    adresse = models.CharField("adresse",max_length=100, blank=True, null=True)
    telephone = models.CharField("telephone", max_length=11, blank=True, null=True)
    email= models.EmailField(_("couriel"), max_length=254)
    sections = models.ForeignKey(Section, related_name='section', on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Commanderie")
        verbose_name_plural = _("Commanderies")
        
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Commanderie_detail",kwargs={"pk": self.pk})
    







TYPE_CHEVALIER= (
    ('CHEVALIER', 'CHEVALIER'),
    ('DAME OXILLIAIRE', 'DAME OXILLIAIRE'),
    ('JUNIOR', 'JUNIOR'),
    ('SENIOR', 'SENIOR'),
) 

TYPE_GARDE= (
    ('MAJOR', 'MAJOR'),
    ('BRIGADIER GENERAL', 'BRIGADIER GENERAL'),
    ('OFFICIE', 'OFFICIE'),
) 

class Chevalier(models.Model):
    fisrt_name = models.CharField("nom",max_length=100, blank=False, null=False)
    last_name = models.CharField("prénom",max_length=100, blank=False, null=False)
    type_chevalier= models.CharField("type de chevalier", max_length=100, choices =TYPE_CHEVALIER, default=[0])
    grade_chevalier= models.CharField("type de grade", max_length=100, choices= TYPE_GARDE, default=[0])
    date = models.DateField(_("date d'initiation"), auto_now=False, blank=False, null=False)
    telephone = models.CharField("telephone",max_length=11, blank=False, null=False)
    adresse = models.CharField("adresse",max_length=100, blank=False, null=False)
    profession = models.CharField("profession",max_length=100, blank=False, null=False)
    commanderie = models.ForeignKey(Commanderie, related_name='commanderie', on_delete=models.CASCADE)
    

    class Meta:
        verbose_name = _("Chevalier")
        verbose_name_plural = _("Chevaliers")

    def __str__(self):
        return self.fisrt_name

    def get_absolute_url(self):
        return reverse("chevalier_detail", kwargs={"pk": self.pk})
    

    
class Bureau(models.Model):
    president =  models.CharField("président", max_length=100, blank=True, null=True )
    vice_president =  models.CharField("vice président", max_length=100, blank=True, null=True )
    secrtaire =  models.CharField("secretaire", max_length=100, blank=True, null=True )
    vice_secretaire = models.CharField("vice secretaire", max_length=100, blank=True, null=True )
    tresorier = models.CharField("tresorier", max_length=100, blank=True, null=True )
    vice_tresorier =  models.CharField("vice tresorier", max_length=100, blank=True, null=True )
    date = models.DateField(_("date d'installation"), auto_now=False)
    commanderie =  models.ForeignKey(Commanderie, verbose_name='commanderie', on_delete=models.CASCADE)
    

    class Meta:
        verbose_name = _("Bureau")
        verbose_name_plural = _("Bureaux")

    def __str__(self):
        return self.president

    def get_absolute_url(self):
        return reverse("bureau_detail", kwargs={"pk": self.pk})

        

districte/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class Districte(models.Model):
    name = models.CharField("nom districte", max_length=100, blank=True, null=True)
    date = models.DateField(_("date de création"), auto_now=False)
    adresse = models.CharField("adresse",max_length=100, blank=True, null=True)
    telephone = models.CharField("telephone", max_length=11, blank=True, null=True)
    email= models.EmailField(_("couriel"), max_length=254)
    

    class Meta:
        verbose_name = _("Districte")
        verbose_name_plural = _("Districtes")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("districte_detail", kwargs={"pk": self.pk})

class Section(models.Model):
    name = models.CharField("nom section",max_length=100, blank=True, null=True)
    date = models.DateField(_("date de création"), auto_now=False)
    adresse = models.CharField("adresse",max_length=100, blank=True, null=True)
    telephone = models.CharField("telephone", max_length=11, blank=True, null=True)
    email= models.EmailField(_("couriel"), max_length=254)
    districtes = models.ForeignKey(Districte, verbose_name='districte', on_delete=models.CASCADE)
    

    class Meta:
        verbose_name = _("Section")
        verbose_name_plural = _("Sections")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("section_detail", kwargs={"pk": self.pk})

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Article, Categorie

# Create your views here.
def index (request):
    name = Article.objects.get(categories=1)
    print(name)
    return render(request, 'blog/index.html', {'name': name})




def un_article(request, id):
    affiche= Article.objects.get(pk=id)
    return render(request, 'blog/all_articles.html', {"affiche":affiche})

commanderie/views.py
from django.shortcuts import render

# Create your views here.
def commandview (request, command):
    nomprod = Article.objects.all()
    return render(request, {'nomprod': nomprod})

districte/views.py
from django.shortcuts import render

# Create your views here.
def indexdist (request):
    nom = Article.objects.all()
    return render(request, {'nom': nom})

templates/base.html
 {% load staticfiles %}
<!DOCTYPE html>
<html lang="en">



<head>
    {%block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>saint jonh</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/modern-business.css' %}" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="assets/images/icon/favicon.ico%}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/metisMenu.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.min.css' %}">
    <!-- amchart css -->


    <!-- others css -->
    <link rel="stylesheet" href="{% static 'assets/css/typography.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/default-css.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css'  %}">
    <!-- modernizr css -->
    <script src="{% static 'assets/js/vendor/modernizr-2.8.3.min.js' %}"></script>
    {% endblock head %}
</head>

<body style="margin: 15px">
    {% block sidebar %}
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="index.html">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="Dashboard.html">Tableau de Bord</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">Qui somme-nous</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">Aide</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    {% endblock sidebar %}
    <header style="margin-top: -15">
        {% block header %}

        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <!-- Slide One - Set the background image for this slide in the line below -->
                <div class="carousel-item active" style="background-image: url({% static '/images/photo.jpg' %})">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>First Slide</h3>
                        <p>This is a description for the first slide.</p>
                    </div>
                </div>
                <!-- Slide Two - Set the background image for this slide in the line below -->
                <div class="carousel-item" style="background-image: url({% static '/images/photoa.jpg' %})">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Second Slide</h3>
                        <p>This is a description for the second slide.</p>
                    </div>
                </div>
                <!-- Slide Three - Set the background image for this slide in the line below -->
                <div class="carousel-item" style="background-image: url({% static '/images/photob.jpg' %})">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Third Slide</h3>
                        <p>This is a description for the third slide.</p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        {% endblock header %}
    </header>{% block content %} {% endblock content %}

    <footer class="py-5 bg-dark">
        {% block footer %}
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
        </div>
        <!-- /.container -->
        {%endblock footer%}
    </footer>

    {% block script %}
    <script src="{% static 'vendor/jquery/jquery.min.js ' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js ' %}"></script>


    <script src="{% static 'assets/js/vendor/jquery-2.2.4.min.js' %}"></script>
    <!-- bootstrap 4 js -->
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/metisMenu.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>
    <!-- all line chart activation -->
    <script src="{% static 'assets/js/line-chart.js' %}"></script>
    <!-- all pie chart -->
    <script src="{% static 'assets/js/pie-chart.js' %}"></script>
    <!-- others plugins -->
    <script src="{% static 'assets/js/plugins.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>
    {% endblock script %}
</body>

</html>

templates/blog/all_articles.html
{% extends "base.html" %}{% load staticfiles %}{% block content %}
<li><a href="{% url 'blog:un_article' id %}">{{ affiche}}</a></li>{% endblock content %}

templates/blog/index.html
{% extends "base.html" %}{% load staticfiles %}{% block content %}


<h1 class="my-4">Welcome to Modern Business</h1>

<!-- Marketing Icons Section -->
<div class="row">
    <div class="col-lg-4 ">
        <div class="card h-100 card-bordered">
            <h4 class="card-header">Titre Article</h4>
            <div class="card-body">
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-primary">Decouvrez-en</a>
            </div>
        </div>
    </div>
    <div class="col-lg-4 ">
        <div class="card h-100 card-bordered">
            <h4 class="card-header">{{name.name}}</h4>
            <div class="card-body">
                <p class="card-text">{{name.picture}}
                </p>
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-primary">Decouvrez-en</a> {{name.publication}}
            </div>
        </div>
    </div>
    <div class="col-lg-4 ">
        <div class="card h-100 card-bordered">
            <h4 class="card-header">Titre Article</h4>
            <div class="card-body">
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-primary">Decouvrez-en</a>

            </div>
        </div>
    </div>
</div>
{%endblock content %}